Feature: Able to customize crudactions and speeddial buttons
kingscode/vuetify-resource pull request #95
Opened 2020-11-09 15:06 UTC by martn001

2020-11-09 21:32 UTC, jvhellemondt approved these changes

2020-11-09 21:32 UTC, jvhellemondt commented on src/VuetifyResource.vue
> +            edit: this.colors.onlyCrudActions ? this.colors.all : this.colors.edit,
All is een standaard ofzo?

2020-11-10 07:30 UTC, ricardovanlaarhoven requested changes
I'm missing the documentation update in the readme.md
And this is a new feature so it can't be a new hotfix version.
this should get a new minor version.

2020-11-10 07:30 UTC, ricardovanlaarhoven commented on src/VuetifyResource.vue
> +            edit: this.colors.onlyCrudActions ? this.colors.all : this.colors.edit,
Perhaps `default` would be better

2020-11-18 10:36 UTC, ricardovanlaarhoven approved these changes
Approved if this is tested in a real project and this feature works, it doesn't break anything and you can still change vuetify's sass variables.

2020-11-18 11:59 UTC, merged

2020-11-18 14:33 UTC, jvhellemondt commented on src/VuetifyResource.vue
> +        },
Goed -- maar veel herhaling.

2020-11-18 14:34 UTC, jvhellemondt commented on src/VuetifyResource.vue
> +        crudIconSize: () => VuetifyResourceOptions.style.default ? VuetifyResourceOptions.style.default.size : null,
Inconsistent met voorgaande computed. ` crudIconSize() {VuetifyResourceOptions.style.default ? VuetifyResourceOptions.style.default.size : null}`